
package com.pado.quickbookbridge.pojos;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "TroubleshootWebServiceFSSoap", targetNamespace = "http://developer.intuit.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TroubleshootWebServiceFSSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://developer.intuit.com/serverVersion")
    @WebResult(name = "serverVersionResult", targetNamespace = "http://developer.intuit.com")
    @RequestWrapper(localName = "serverVersion", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.ServerVersion")
    @ResponseWrapper(localName = "serverVersionResponse", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.ServerVersionResponse")
    public String serverVersion();

    /**
     * 
     * @param strVersion
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://developer.intuit.com/clientVersion")
    @WebResult(name = "clientVersionResult", targetNamespace = "http://developer.intuit.com")
    @RequestWrapper(localName = "clientVersion", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.ClientVersion")
    @ResponseWrapper(localName = "clientVersionResponse", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.ClientVersionResponse")
    public String clientVersion(
        @WebParam(name = "strVersion", targetNamespace = "http://developer.intuit.com")
        String strVersion);

    /**
     * 
     * @param strUserName
     * @param strPassword
     * @return
     *     returns com.pado.quickbookbridge.pojos.ArrayOfString
     */
    @WebMethod(action = "http://developer.intuit.com/authenticate")
    @WebResult(name = "authenticateResult", targetNamespace = "http://developer.intuit.com")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.AuthenticateResponse")
    public ArrayOfString authenticate(
        @WebParam(name = "strUserName", targetNamespace = "http://developer.intuit.com")
        String strUserName,
        @WebParam(name = "strPassword", targetNamespace = "http://developer.intuit.com")
        String strPassword);

    /**
     * This web method facilitates web service to handle connection error between QBWC and QB
     * 
     * @param hresult
     * @param ticket
     * @param message
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://developer.intuit.com/connectionError")
    @WebResult(name = "connectionErrorResult", targetNamespace = "http://developer.intuit.com")
    @RequestWrapper(localName = "connectionError", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.ConnectionError")
    @ResponseWrapper(localName = "connectionErrorResponse", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.ConnectionErrorResponse")
    public String connectionError(
        @WebParam(name = "ticket", targetNamespace = "http://developer.intuit.com")
        String ticket,
        @WebParam(name = "hresult", targetNamespace = "http://developer.intuit.com")
        String hresult,
        @WebParam(name = "message", targetNamespace = "http://developer.intuit.com")
        String message);

    /**
     * This web method facilitates web service to send request XML to QuickBooks via QBWebConnector
     * 
     * @param qbXMLMinorVers
     * @param qbXMLCountry
     * @param ticket
     * @param qbXMLMajorVers
     * @param strCompanyFileName
     * @param strHCPResponse
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://developer.intuit.com/sendRequestXML")
    @WebResult(name = "sendRequestXMLResult", targetNamespace = "http://developer.intuit.com")
    @RequestWrapper(localName = "sendRequestXML", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.SendRequestXML")
    @ResponseWrapper(localName = "sendRequestXMLResponse", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.SendRequestXMLResponse")
    public String sendRequestXML(
        @WebParam(name = "ticket", targetNamespace = "http://developer.intuit.com")
        String ticket,
        @WebParam(name = "strHCPResponse", targetNamespace = "http://developer.intuit.com")
        String strHCPResponse,
        @WebParam(name = "strCompanyFileName", targetNamespace = "http://developer.intuit.com")
        String strCompanyFileName,
        @WebParam(name = "qbXMLCountry", targetNamespace = "http://developer.intuit.com")
        String qbXMLCountry,
        @WebParam(name = "qbXMLMajorVers", targetNamespace = "http://developer.intuit.com")
        int qbXMLMajorVers,
        @WebParam(name = "qbXMLMinorVers", targetNamespace = "http://developer.intuit.com")
        int qbXMLMinorVers);

    /**
     * This web method facilitates web service to receive response XML from QuickBooks via QBWebConnector
     * 
     * @param hresult
     * @param ticket
     * @param response
     * @param message
     * @return
     *     returns int
     */
    @WebMethod(action = "http://developer.intuit.com/receiveResponseXML")
    @WebResult(name = "receiveResponseXMLResult", targetNamespace = "http://developer.intuit.com")
    @RequestWrapper(localName = "receiveResponseXML", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.ReceiveResponseXML")
    @ResponseWrapper(localName = "receiveResponseXMLResponse", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.ReceiveResponseXMLResponse")
    public int receiveResponseXML(
        @WebParam(name = "ticket", targetNamespace = "http://developer.intuit.com")
        String ticket,
        @WebParam(name = "response", targetNamespace = "http://developer.intuit.com")
        String response,
        @WebParam(name = "hresult", targetNamespace = "http://developer.intuit.com")
        String hresult,
        @WebParam(name = "message", targetNamespace = "http://developer.intuit.com")
        String message);

    /**
     * 
     * @param ticket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://developer.intuit.com/getLastError")
    @WebResult(name = "getLastErrorResult", targetNamespace = "http://developer.intuit.com")
    @RequestWrapper(localName = "getLastError", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.GetLastError")
    @ResponseWrapper(localName = "getLastErrorResponse", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.GetLastErrorResponse")
    public String getLastError(
        @WebParam(name = "ticket", targetNamespace = "http://developer.intuit.com")
        String ticket);

    /**
     * 
     * @param ticket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://developer.intuit.com/closeConnection")
    @WebResult(name = "closeConnectionResult", targetNamespace = "http://developer.intuit.com")
    @RequestWrapper(localName = "closeConnection", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.CloseConnection")
    @ResponseWrapper(localName = "closeConnectionResponse", targetNamespace = "http://developer.intuit.com", className = "com.pado.quickbookbridge.pojos.CloseConnectionResponse")
    public String closeConnection(
        @WebParam(name = "ticket", targetNamespace = "http://developer.intuit.com")
        String ticket);

}
